### ISSUE TITLE
Location of KextUrl.txt has changed and links do not work

### ISSUE THREAD

**Issue by chriswayg** [5T33Z0/OC-Little-Translated#119]
https://github.com/5T33Z0/OC-Little-Translated/blob/main/14_OCLP_Wintel/Guides/Fetching_OCLP_Kexts.md

### Locations
Old location:
/OCAuxiliaryTools.app/Contents/MacOS/Database/preset/KextUrl.txt

Recent location: 
/Users/username/.ocat/Database/preset/KextUrl.txt

Current new Location:
/Users/username/.config/OCAuxiliaryTools/KextUrl.txt

### Links
Links that do not work: (I only tested these)
- AMFIPass.kext | https://github.com/dortania/OpenCore-Legacy-Patcher
- IO80211FamilyLegacy.kext | https://github.com/dortania/OpenCore-Legacy-Patcher
- IOSkywalkFamily.kext | https://github.com/dortania/OpenCore-Legacy-Patcher 

I think OCAuxiliaryTools looks for a Github Release with that kext, not the zip file:
https://github.com/dortania/OpenCore-Legacy-Patcher/tree/main/payloads/Kexts/Wifi

**Comment by 5T33Z0** [comment]
1. I chose to use the KextUrl location _inside_ the app because the user section does not have a `preset` folder for DEV mode (`devDatabase` ). The devDatabase is used when downloading nightly builds of OpenCore and kexts. The kexturl file in the app is globally used for both modes (normal/dev) , that's why the guide refers to that
2. I think the `.config` folder this is a temporary location. In my case it only contains 3 .ini files (in macOS)
3. The kexts from OpenCore Legacy patcher will be fetched if the link is in the kexturl file inside the app. But the app has to be restarted after adding links to the list. 
4. Example: `AMFIPass.kext`:
- Without the `AMFIPass.kext | https://github.com/dortania/OpenCore-Legacy-Patcher` entry, the entry has a gray square, indicating that the kext can't be found: <br>![gray](https://github.com/user-attachments/assets/a024ad3c-c7ad-4555-81fb-cb7b87d7ccb9)
- With the `AMFIPass.kext | https://github.com/dortania/OpenCore-Legacy-Patcher` entry, the entry becomes green, since it can be found and compared: <br>![green](https://github.com/user-attachments/assets/45b3e4cd-29f2-4ceb-bb9f-a981a55ee13a)

**Comment by 5T33Z0** [comment]
After further tests I heve noticed that OCLP actually does not fetch the kexts in the list. I've added an older version of AMFIPass and then tried to update it - but it didn't fetch the newer version - so the "green" indicator is misleading in this case. I have removed this guide.
