### ISSUE TITLE
ASRock motherboards LED controller issue and fix

### ISSUE THREAD

**Issue by amane1234** [5T33Z0/OC-Little-Translated#121]
On certain ASRock motherboards (confirmed models: A520M-ITX/ac and B550M Pro4), the LEDs cannot be turned off using the shutdown or reboot buttons in Hackintosh macOS, which causes a black screen during POST after restarting the system.

This issue can be resolved by disabling the LED controller port during the USB mapping process.

![reboot-and-shutdown-problem-on-asrock-boards-with-b550m-v0-rjc3bmgxgzpd1-ezgif com-webp-to-jpg-converter](https://github.com/user-attachments/assets/84b0f084-5929-469b-8774-007529740ae9)
(Source: https://www.reddit.com/r/hackintosh/comments/1flewc3/reboot_and_shutdown_problem_on_asrock_boards_with/)

I believe this issue only occurs with ASRock motherboards, and I hope there is a section in your repository ([03_USB_Fixes](https://github.com/5T33Z0/OC-Little-Translated/tree/main/03_USB_Fixes) would be great) that addresses this problem.

**Comment by 5T33Z0** [comment]
Thanks for reporting. I've added a note to the "Fixing USB issues" section. I think the underlying problem could be that the USB 1.1 prrtotcol that these LED controllers use, was dropped from macOS Ventura onward. But only for older SMBIOSes, though. So I am uncertain. Anyway, I've recommended to disable such port for all desktop mainboards since real Macs don't have RGB fans anyay ;)
