### ISSUE TITLE
SSDT-PTSWAKTTS...?

### ISSUE THREAD

**Issue by Lucke77** [5T33Z0/OC-Little-Translated#50]
Hi Guys and congratulations 5T33Z0 for the immense work you have done, it was very helpful to me to revive an old Haswell 2014 laptop. My question is: I am trying to integrate the SSDT-PTSWAKTTS, but the system does not create me the PCI9 Device for inserting patches (in IORegistryExplorer it is present only under: ACPIPlane but not in IOService). Do I forget or am I wrong something? Thanks in advance...!

**Comment by 5T33Z0** [comment]
Hi and thanks for the compliments. It's highly appreciated, although I am just standing on the shoulders of giants. 

I am using this patch on my Laptop as well. I never actually checked for the `PCI9` device really, most of my sleep/wake issues were resolved after adding it.

You can't find it in the default view (IOService) since well – it's not a service. ;) If you switch to IOACPIPlane, you will find it. 

![Bildschirmfoto 2022-08-20 um 15 46 59](https://user-images.githubusercontent.com/76865553/185749094-65f02e6e-0ae0-447b-9962-b2239f0b91fc.png)
