### ISSUE TITLE
[Graphics] Disabling unsupported GPU

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/OC-Little-Translated#67]
Hi, and thank you so much for the shared knowledge over the months.
I actually came up to [this page](https://github.com/5T33Z0/OC-Little-Translated/tree/main/11_Graphics/GPU/Disabling_unsupported_GPUs) that explains how to disable unsupported GPUs but noticed a few errors:

1. Both `-wegnoegpu` and `disable-external-gpu` require `WhateverGreen.kext` injected
2. In case of multiple dGPUs systems (e.g. 4090+RX6800XT) the wisest way would be, after proper checking the definition of `pci-bridge`s, use `DeviceProperties` and therefore use `disable-gpu` property.

I hope you will find this info useful somehow.
Have a nice day

--
dreamwhite

**Comment by 5T33Z0** [comment]
Hi. The things you point out are no "errors".

1. The requirement for `Whatevergreen` is mentioned in the instructions already!
2. What applies to disabling a single GPU is also applicable for  a system with multiple GPUs. The only difference is a PCI Address.

**Comment by dreamwhite** [comment]
1. Sorry for the misunderstanding. What I was actually talking about is that only `-wegnoegpu` requires WhateverGreen, as far as I read the guide. I perfectly know your intentions, but it's not that clear actually.


![image](https://user-images.githubusercontent.com/17933708/218471164-9a7b06e9-1ee2-4520-9d2c-166f01be9b5d.png)

2. With the SSDT it's fine, but in case of `DeviceProperties`, `disable-external-gpu` actually disables ALL the external GPUs rather than just a single one (which can be achieved by using `disable-gpu`)

**Comment by 5T33Z0** [comment]
How can  a DeveiceProperty injected into a single device disable ALL GPUS? For the boot-arg yes, I understand it, but for the DevProp, I ann pressty sure it only disables the device it is injected into – otherwise there would be no need to have it at all. It actually states "disable-gpu property to each GFX0" for the device property in the Whatevergreen repo.

I will update the info for Option 1 and add Option 3 for the rare edge case of multiple GPUs
