### ISSUE TITLE
hi will there be laptop configs anywhere for this proramme 

### ISSUE THREAD

**Issue by danny1m** [5T33Z0/OC-Little-Translated#79]
I'm specifically looking for a laptop ice lake 10th gen i3 CPU

**Comment by 5T33Z0** [comment]
Hi. 

No, there won't.

 Because:

1.  Laptops are pretty unique in terms of configuration and ACPI hotfix requirements. 
2. Getting modern Laptops to work is pretty simple. But getting all the minute details to work well (Clamshell mode, Sleep/wake, Power LED behavior and enabling external screens) takes a lot of time and patience and individual patches. 
3. I can't take everything in consideration that would be required and stuff it in a config. And even though I could do that, users would have to spend a lot of time editing the config prior to deployment anyway.
4. There's a github repo which collects all tyes of availabe Laptop EFIs: https://github.com/daliansky/Hackintosh

**Comment by danny1m** [comment]
Thanks got the setup booting using your efi and adding my usbmap from the US toolbox app ran on windows  I configured the efi using the opencore auxiliary tools which seamed to work well.
