### ISSUE TITLE
RestrictEvents now have VMM patch

### ISSUE THREAD

**Issue by gujiangjiang** [5T33Z0/OC-Little-Translated#87]
Before I‘m using these patches to make macOS install and boot with unsupported SMBIOS:
![截屏2023-09-27 22 38 52](https://github.com/5T33Z0/OC-Little-Translated/assets/13273955/f6c85db7-c61b-48b3-b452-bdaae4371ec4)

But today I find the [RestrictEvents](https://github.com/acidanthera/RestrictEvents) have update with VMM support so I tried the new commit.
1. Delete all the vmm kernel patch but reserve the 2 boot patches.
2. Using the  RestrictEvents with new commit.
3. Stay boot-arg: revpatch=sbvmm.
4. Reboot and it works.

I have tested in install and macOS have no problem.

But when into macOS the
`kern.hv_vmm_present: 0`
![截屏2023-09-27 22 43 23](https://github.com/5T33Z0/OC-Little-Translated/assets/13273955/5b9db528-1f86-462f-bf1f-b5337a6f69f2)

**Comment by gujiangjiang** [comment]
and I find the vmm kernel patches may block my bluetooth to work.
buletooth can on and off but can't serch any devices.
delete the vmm kernel patches the bluetooth works again with RestrictEvents(new commit)

My bluetooth was BCM20702A0

**Comment by 5T33Z0** [comment]
1. My [instructions](https://github.com/5T33Z0/OC-Little-Translated/tree/main/09_Board-ID_VMM-Spoof#system-requirements) for implementing the Board-Id VMM Patch already cover that you can use the RestricEvents.kext instead of the Kernel Patches if you only need it for fixing System Update Notifications.
2. The `kern.hv_vmm_present` test is only applicable when using the Kernel Patches, not the RestrictEvents.kext
3. I am using the Kernel Patches on my Laptop and it doesn't affect Bluetooth so I cannot confirm this. In this case you have to report this to the devs of OpenCore Legacy Patcher.

**Comment by gujiangjiang** [comment]
@5T33Z0 
Thanks for your replay.

Another bug when using clover inject AppleIntelCPUPowerManagement.kext cause kernel panic.
[AppleIntelCPUPowerManagement.kext](https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/CPU_Power_Management/CPU_Power_Management_(Legacy)#re-enabling-acpi-power-management-in-macos-ventura)
But using OpenCore with no problem.
Any solution to using AppleIntelCPUPowerManagement.kext in Clover?

Thanks again.

**Comment by 5T33Z0** [comment]
I have Clover working on my T530.

But at some point I had to delete the whole CLOVER folder and start from scratch using the latest nightly build (It's available under the "Actions" Tab of the Clover repo.
