### ISSUE TITLE
App Refresh for Opencore + Varius Bug Fix

### ISSUE THREAD

**Issue by Baio1977** [5T33Z0/OC-Little-Translated#98]
https://github.com/Baio1977/GenI2C_Refresh

I am developing this application to work with Opencore.
If you can test it I would be happy to evolve it.
Thank you

**Comment by 5T33Z0** [comment]
Unfortunately, I don't have a laptop that uses I2C to control the touchpad, so I can't test it but I can add it to the "Utilities and Resources" list.

**Comment by Baio1977** [comment]
Ok, that's fine too, little by little I will improve the project.
Anyone who has 1 Laptop with I2C is asked to test GenI2C_Refresh and perhaps leave an opinion in the reposity of my Fork.
[GenI2C_Refresh](https://github.com/Baio1977/GenI2C_Refresh)

**Comment by 5T33Z0** [comment]
Okay. I've noticed an issue with your tool when it comes to openening the DSDT: the dialoge window is always somewhere on the left corner and can't be moved: 

![Bildschirmfoto 2024-01-03 um 19 31 33](https://github.com/5T33Z0/OC-Little-Translated/assets/76865553/9a623bac-e885-4591-8d3a-e942849305a9)

Maybe you can adjust this somehow so that it openes centered on top of the app.

**Comment by 5T33Z0** [comment]
Added GenI2C_Refreh to Utilities and Trackpad Patches sections.

**Comment by Baio1977** [comment]
https://github.com/Baio1977/GenI2C 
I rebuilt the project, kept ALL the previous functions (rename Clover Bootloader) and added all the fixes made in the previous Reposity.

The window now opens correctly
![Screenshot 2024-01-07 alle 10 03 52](https://github.com/5T33Z0/OC-Little-Translated/assets/59058746/1f9363ad-614a-4fa8-b766-91435deb3123)

Thanks for all <3
